"""
Branch Operations & Hierarchy Realignment Engine.

Enforces forward-slash (/) organizational folder hierarchy across Git branches
and worktrees:
- Standalone quests: quest/<quest_id>-<slug>
- Epic child quests: quest/<epic_id>/<quest_id>-<slug>
- Epics: epic/<epic_id>-<slug>
- Scout spikes: scout/<quest_id>-<slug> or scout/<epic_id>/<quest_id>-<slug>
- Gatehouse stations: the-gatehouse/<station>

Automates repair of flat-hyphen sanitized branches generated by Agent Manager
(e.g. quest-q084-..., quest-q014-q088-..., scout-q074-..., the-gatehouse-north).
"""
from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Any, Optional

from . import git_ops
from .models import Quest, validate_branch_name

# Regex patterns for flat hyphen branch names
_FLAT_GATEHOUSE_RE = re.compile(r"^the-gatehouse-(north|south|east|west|central|bastion.*)$", re.IGNORECASE)
_FLAT_EPIC_CHILD_QUEST_RE = re.compile(r"^quest-(q\d+)-(q\d+)-(.*)$", re.IGNORECASE)
_FLAT_EPIC_CHILD_SCOUT_RE = re.compile(r"^scout-(q\d+)-(q\d+)-(.*)$", re.IGNORECASE)
_FLAT_EPIC_RE = re.compile(r"^epic-(q\d+)-(.*)$", re.IGNORECASE)
_FLAT_STANDALONE_QUEST_RE = re.compile(r"^quest-(q\d+)-(.*)$", re.IGNORECASE)
_FLAT_STANDALONE_SCOUT_RE = re.compile(r"^scout-(q\d+)-(.*)$", re.IGNORECASE)


def find_quest_in_court(quest_id_or_num: str, cwd: Optional[Path | str] = None) -> Optional[Quest]:
    """Look up a Quest or Epic by its ID number or string in .court/ directory."""
    try:
        from . import store
        bare = quest_id_or_num.lower().lstrip("q")
        court_root = store.get_court_root(cwd)
        q = store.find_path(quest_id_or_num, court_root=court_root)
        if q and q.exists():
            return Quest.from_markdown(q.read_text(encoding="utf-8"))
        if bare.isdigit():
            q = store.find_path(f"Q{int(bare):03d}", court_root=court_root)
            if q and q.exists():
                return Quest.from_markdown(q.read_text(encoding="utf-8"))
    except Exception:
        pass
    return None


def resolve_canonical_branch_name(
    branch_name: str,
    cwd: Optional[Path | str] = None,
) -> tuple[str, str]:
    """
    Given a branch name (flat or nested), return (canonical_slash_name, reason).
    """
    clean = branch_name.strip()
    if clean.startswith("refs/heads/"):
        clean = clean[len("refs/heads/"):]

    if not clean:
        return "", "empty"

    if clean in ("main", "castle"):
        return clean, "trunk"

    m_gh = _FLAT_GATEHOUSE_RE.match(clean)
    if m_gh:
        station = m_gh.group(1).lower()
        return f"the-gatehouse/{station}", "gatehouse_flat_to_slash"

    if clean.startswith("the-gatehouse/"):
        return clean, "canonical_gatehouse"

    m_child_q = _FLAT_EPIC_CHILD_QUEST_RE.match(clean)
    if m_child_q:
        epic_id = m_child_q.group(1).lower()
        child_id = m_child_q.group(2).lower()
        slug = m_child_q.group(3).lower()

        quest = find_quest_in_court(child_id, cwd=cwd)
        if quest and quest.branch and quest.branch.startswith(f"quest/{epic_id}/"):
            return quest.branch, f"court_quest_frontmatter ({quest.id})"
        elif quest and quest.tree_branch and quest.tree_branch.startswith(f"quest/{epic_id}/"):
            return quest.tree_branch, f"court_quest_tree_branch ({quest.id})"

        return f"quest/{epic_id}/{child_id}-{slug}", "regex_child_quest"

    m_child_s = _FLAT_EPIC_CHILD_SCOUT_RE.match(clean)
    if m_child_s:
        epic_id = m_child_s.group(1).lower()
        child_id = m_child_s.group(2).lower()
        slug = m_child_s.group(3).lower()

        quest = find_quest_in_court(child_id, cwd=cwd)
        if quest and quest.branch and quest.branch.startswith(f"scout/{epic_id}/"):
            return quest.branch, f"court_scout_frontmatter ({quest.id})"
        elif quest and quest.tree_branch and quest.tree_branch.startswith(f"scout/{epic_id}/"):
            return quest.tree_branch, f"court_scout_tree_branch ({quest.id})"

        return f"scout/{epic_id}/{child_id}-{slug}", "regex_child_scout"

    m_epic = _FLAT_EPIC_RE.match(clean)
    if m_epic:
        epic_id = m_epic.group(1).lower()
        slug = m_epic.group(2).lower()

        quest = find_quest_in_court(epic_id, cwd=cwd)
        if quest and quest.branch and quest.branch.startswith("epic/"):
            return quest.branch, f"court_epic_frontmatter ({quest.id})"
        elif quest and quest.tree_branch:
            return quest.tree_branch, f"court_epic_tree_branch ({quest.id})"

        return f"epic/{epic_id}-{slug}", "regex_epic"

    m_stand_q = _FLAT_STANDALONE_QUEST_RE.match(clean)
    if m_stand_q:
        quest_id = m_stand_q.group(1).lower()
        slug = m_stand_q.group(2).lower()

        fork_suffix = ""
        m_fork = re.search(r"(-\d+)$", clean)
        if m_fork:
            fork_suffix = m_fork.group(1)

        quest = find_quest_in_court(quest_id, cwd=cwd)
        if quest:
            reason_suffix = "_fork" if fork_suffix else ""
            if quest.branch and quest.branch.startswith("quest/"):
                b = quest.branch
                if fork_suffix and not b.endswith(fork_suffix):
                    b = f"{b}{fork_suffix}"
                return b, f"court_quest_frontmatter{reason_suffix} ({quest.id})"
            elif quest.tree_branch:
                b = quest.tree_branch
                if fork_suffix and not b.endswith(fork_suffix):
                    b = f"{b}{fork_suffix}"
                return b, f"court_quest_tree_branch{reason_suffix} ({quest.id})"

        return f"quest/{quest_id}-{slug}", "regex_standalone_quest"

    m_stand_s = _FLAT_STANDALONE_SCOUT_RE.match(clean)
    if m_stand_s:
        quest_id = m_stand_s.group(1).lower()
        slug = m_stand_s.group(2).lower()

        fork_suffix = ""
        m_fork = re.search(r"(-\d+)$", clean)
        if m_fork:
            fork_suffix = m_fork.group(1)

        quest = find_quest_in_court(quest_id, cwd=cwd)
        if quest:
            if quest.branch and quest.branch.startswith("scout/"):
                b = quest.branch
                if fork_suffix and not b.endswith(fork_suffix):
                    b = f"{b}{fork_suffix}"
                return b, f"court_scout_frontmatter ({quest.id})"
            elif quest.tree_branch:
                b = quest.tree_branch
                if fork_suffix and not b.endswith(fork_suffix):
                    b = f"{b}{fork_suffix}"
                return b, f"court_scout_tree_branch ({quest.id})"

        return f"scout/{quest_id}-{slug}", "regex_standalone_scout"

    if clean.startswith(("quest/", "scout/", "epic/")):
        parts = clean.split("/")
        last_part = parts[-1]
        m_id = re.match(r"^(q\d+)", last_part, re.IGNORECASE)
        if m_id:
            quest_id = m_id.group(1).lower()
            quest = find_quest_in_court(quest_id, cwd=cwd)
            if quest and quest.branch and len(quest.branch) > len(clean) and quest.branch.startswith(clean[:len(parts[0])]):
                return quest.branch, f"untruncate_from_court ({quest.id})"
        return clean, "already_canonical"

    return clean, "unrecognized_format"


def get_all_local_branches(cwd: Optional[Path | str] = None) -> dict[str, str]:
    """Return dict mapping local branch name to commit SHA."""
    root = git_ops.get_repo_root(cwd)
    res = git_ops._run(["git", "for-each-ref", "--format=%(refname:short) %(objectname)", "refs/heads/"], root)
    branches = {}
    if res.get("ok") and res.get("stdout"):
        for line in res["stdout"].splitlines():
            line = line.strip()
            if line:
                parts = line.split()
                if len(parts) >= 2:
                    branches[parts[0]] = parts[1]
    return branches


def realign_all_branches(
    dry_run: bool = False,
    cwd: Optional[Path | str] = None,
) -> dict[str, Any]:
    """Scan all local git branches and worktrees, renaming flat branches to slash hierarchy."""
    root = git_ops.get_repo_root(cwd)
    worktrees = git_ops.list_git_worktrees(root)
    local_branches = get_all_local_branches(root)

    checked_out_branches: dict[str, dict] = {}
    for wt in worktrees:
        b = wt.get("branch")
        if b:
            checked_out_branches[b] = wt

    actions: list[dict[str, Any]] = []
    skipped: list[dict[str, Any]] = []
    errors: list[dict[str, Any]] = []

    for branch_name, sha in list(local_branches.items()):
        canonical, reason = resolve_canonical_branch_name(branch_name, cwd=root)

        if canonical == branch_name:
            continue

        wt_info = checked_out_branches.get(branch_name)
        wt_path = Path(wt_info["worktree"]) if wt_info else None
        is_checked_out = bool(wt_info and wt_path and wt_path.exists())

        action_entry = {
            "old_branch": branch_name,
            "new_branch": canonical,
            "reason": reason,
            "sha": sha,
            "checked_out": is_checked_out,
            "worktree_path": str(wt_path) if wt_path else None,
            "action_taken": None,
            "ok": True,
        }

        canonical_exists = canonical in local_branches or git_ops._run(["git", "rev-parse", "--verify", f"refs/heads/{canonical}"], root).get("ok")
        if canonical_exists:
            canonical_wt = checked_out_branches.get(canonical)

            if is_checked_out:
                if canonical_wt and str(canonical_wt.get("worktree")) != str(wt_path):
                    action_entry["ok"] = False
                    action_entry["action_taken"] = "COLLISION_BOTH_CHECKED_OUT"
                    action_entry["error"] = (
                        f"Both '{branch_name}' (at {wt_path}) and '{canonical}' "
                        f"(at {canonical_wt.get('worktree')}) exist and are checked out."
                    )
                    errors.append(action_entry)
                else:
                    if not dry_run:
                        rn_res = git_ops._run(["git", "branch", "-M", branch_name, canonical], wt_path)
                        if rn_res.get("ok"):
                            action_entry["action_taken"] = "FORCE_RENAMED_IN_WORKTREE"
                            local_branches[canonical] = sha
                            local_branches.pop(branch_name, None)
                            checked_out_branches[canonical] = wt_info
                            checked_out_branches.pop(branch_name, None)
                            actions.append(action_entry)
                        else:
                            action_entry["ok"] = False
                            action_entry["action_taken"] = "RENAME_FAILED"
                            action_entry["error"] = rn_res.get("stderr") or rn_res.get("stdout")
                            errors.append(action_entry)
                    else:
                        action_entry["action_taken"] = "WOULD_FORCE_RENAME_IN_WORKTREE"
                        actions.append(action_entry)
            else:
                if not dry_run:
                    del_res = git_ops._run(["git", "branch", "-D", branch_name], root)
                    if del_res.get("ok"):
                        action_entry["action_taken"] = "DELETED_OBSOLETE_FLAT_BRANCH"
                        local_branches.pop(branch_name, None)
                        actions.append(action_entry)
                    else:
                        action_entry["ok"] = False
                        action_entry["action_taken"] = "DELETE_FAILED"
                        action_entry["error"] = del_res.get("stderr") or del_res.get("stdout")
                        errors.append(action_entry)
                else:
                    action_entry["action_taken"] = "WOULD_DELETE_OBSOLETE_FLAT_BRANCH"
                    actions.append(action_entry)
        else:
            if is_checked_out and wt_path:
                if not dry_run:
                    rn_res = git_ops._run(["git", "branch", "-m", branch_name, canonical], wt_path)
                    if rn_res.get("ok"):
                        action_entry["action_taken"] = "RENAMED_IN_WORKTREE"
                        local_branches[canonical] = sha
                        local_branches.pop(branch_name, None)
                        checked_out_branches[canonical] = wt_info
                        checked_out_branches.pop(branch_name, None)
                        actions.append(action_entry)
                    else:
                        action_entry["ok"] = False
                        action_entry["action_taken"] = "RENAME_FAILED"
                        action_entry["error"] = rn_res.get("stderr") or rn_res.get("stdout")
                        errors.append(action_entry)
                else:
                    action_entry["action_taken"] = "WOULD_RENAME_IN_WORKTREE"
                    actions.append(action_entry)
            else:
                if not dry_run:
                    rn_res = git_ops._run(["git", "branch", "-m", branch_name, canonical], root)
                    if rn_res.get("ok"):
                        action_entry["action_taken"] = "RENAMED_LOOSE_BRANCH"
                        local_branches[canonical] = sha
                        local_branches.pop(branch_name, None)
                        actions.append(action_entry)
                    else:
                        action_entry["ok"] = False
                        action_entry["action_taken"] = "RENAME_FAILED"
                        action_entry["error"] = rn_res.get("stderr") or rn_res.get("stdout")
                        errors.append(action_entry)
                else:
                    action_entry["action_taken"] = "WOULD_RENAME_LOOSE_BRANCH"
                    actions.append(action_entry)

    return {
        "ok": len(errors) == 0,
        "dry_run": dry_run,
        "total_scanned": len(local_branches),
        "realigned_count": len(actions),
        "error_count": len(errors),
        "actions": actions,
        "errors": errors,
    }


def realign_current_worktree(
    cwd: Optional[Path | str] = None,
    sync_castle: bool = True,
) -> dict[str, Any]:
    """Ensure the current worktree is on its canonical slash-hierarchy branch
    and fast-forwarded from castle."""
    wt_dir = Path(cwd) if cwd else Path.cwd()
    branch_res = git_ops._run(["git", "rev-parse", "--abbrev-ref", "HEAD"], wt_dir)
    if not branch_res.get("ok"):
        return {"ok": False, "error": f"Failed to get current branch: {branch_res.get('stderr')}"}

    current_branch = branch_res.get("stdout", "").strip()
    canonical, reason = resolve_canonical_branch_name(current_branch, cwd=wt_dir)

    renamed = False
    rename_err = None

    if canonical and canonical != current_branch:
        rn_res = git_ops._run(["git", "branch", "-M", current_branch, canonical], wt_dir)
        if rn_res.get("ok"):
            renamed = True
        else:
            rename_err = rn_res.get("stderr") or rn_res.get("stdout")

    sync_ok = None
    sync_err = None
    if sync_castle:
        ff_res = git_ops._run(["git", "merge", "castle", "--ff-only"], wt_dir)
        sync_ok = ff_res.get("ok")
        if not sync_ok:
            sync_err = ff_res.get("stderr") or ff_res.get("stdout")

    return {
        "ok": rename_err is None and (sync_ok is None or sync_ok is True),
        "previous_branch": current_branch,
        "canonical_branch": canonical or current_branch,
        "renamed": renamed,
        "reason": reason,
        "rename_error": rename_err,
        "sync_castle": sync_ok,
        "sync_error": sync_err,
    }
